### ISSUE TITLE
What's the intuition behind Bart salmon?

### ISSUE THREAD

**Issue by donkawechico** [benmvp/bart-salmon#33]
Hello! I heard you plug this at a react (or was it Ruby?) conf in SF a couple years ago, and I keep thinking back to it.

But I never really understood the intuition behind how you could maximize seat chances by going backwards. At least, not in an automated way.

Are you putting in your own local knowledge of which stations offload the most passengers with fewest onboarding? Is there realtime data on train crowdedness?

I'm probably missing something obvious. Could you help explain? Might be a useful addition to the readme as well.

**Comment by benmvp** [comment]
Good question!

The rationale is that generally the earlier someone gets on a train, the less likely it'll be full. So If I get on a train 2 stops before mine, it won't yet have the passengers from the station before nor those trying to get on at my actual stop. With less passengers aboard, there is a greater likelihood for a seat.

There's additional local knowledge about specific stations, so I know that if I get on a train 3 stops before mine, I'm pretty much guaranteed a seat because folks start getting on at the station 2 before. Other folks have similar information.

Does that make sense?

Good call on explaining it in the README! I'll definitely update that.

**Comment by donkawechico** [comment]
AHhh. That makes sense! I can finally put that bit of confusion to rest in my mind :P 

Thank you!

**Comment by benmvp** [comment]
Very welcome!
